version: '3.8'

services:
  web:
    build: .
    container_name: web
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
  sidekiq:
    build: .
    container_name: sidekiq
    command: bundle exec sidekiq
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
  hutch:
    build: .
    container_name: hutch
    command: bundle exec hutch
    volumes:
      - .:/app
    depends_on:
      - postgres
      - rabbitmq
  postgres:
    image: postgres:17.4-alpine
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
    ports:
      - "5432:5432"
  redis:
    image: redis:7.2.4-alpine
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    volumes: 
      - redis_data:/data
  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"  # RabbitMQ default port
      - "15672:15672"  # RabbitMQ management plugin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  # Persist RabbitMQ data
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
volumes:
  redis_data:
  rabbitmq_data:
  postgres_data: