default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

# change host to "db" for use with docker

development:
  <<: *default
  host:  localhost
  username: postgres
  password: postgres
  database: payment_on_rails_development

test:
  <<: *default
  host: localhost
  username: postgres
  password: postgres
  database: payment_on_rails_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
