name: "Ruby on Rails CI"

on:
  push:
    branches: [ main ]

jobs:
  test:
    name: rspec
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      - uses: actions/checkout@v3

      - name: Use Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3

      - name: Bundle Install
        run: bundle install

      - name: Setup Database
        run: bundle exec rails db:setup

      - name: Run RSpec Tests
        run: bundle exec rspec
  lint:
    name: rubocop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true

      - name: Lint Ruby files
        run: bin/rubocop --parallel
